// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockMarketAPI.Data;

#nullable disable

namespace StockMarketAPI.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20251031154341_AddMoreStocks")]
    partial class AddMoreStocks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("StockMarketAPI.Models.Stock", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Favorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreviousPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Code = "AAPL",
                            Exchange = "NASDAQ",
                            Favorite = true,
                            Name = "Apple Inc.",
                            PreviousPrice = 175.20m,
                            Price = 178.50m
                        },
                        new
                        {
                            Id = "2",
                            Code = "MSFT",
                            Exchange = "NASDAQ",
                            Favorite = true,
                            Name = "Microsoft Corporation",
                            PreviousPrice = 380.1m,
                            Price = 382.75m
                        },
                        new
                        {
                            Id = "3",
                            Code = "AMZN",
                            Exchange = "NASDAQ",
                            Favorite = true,
                            Name = "Amazon.com Inc.",
                            PreviousPrice = 142.9m,
                            Price = 145.25m
                        },
                        new
                        {
                            Id = "4",
                            Code = "GOOGL",
                            Exchange = "NASDAQ",
                            Favorite = false,
                            Name = "Alphabet Inc.",
                            PreviousPrice = 140.2m,
                            Price = 138.65m
                        },
                        new
                        {
                            Id = "5",
                            Code = "META",
                            Exchange = "NASDAQ",
                            Favorite = false,
                            Name = "Meta Platforms Inc.",
                            PreviousPrice = 318.75m,
                            Price = 325.4m
                        },
                        new
                        {
                            Id = "6",
                            Code = "NVDA",
                            Exchange = "NASDAQ",
                            Favorite = true,
                            Name = "NVIDIA Corporation",
                            PreviousPrice = 478.9m,
                            Price = 485.2m
                        },
                        new
                        {
                            Id = "7",
                            Code = "TSLA",
                            Exchange = "NASDAQ",
                            Favorite = true,
                            Name = "Tesla Inc.",
                            PreviousPrice = 238.75m,
                            Price = 242.50m
                        },
                        new
                        {
                            Id = "8",
                            Code = "JPM",
                            Exchange = "NYSE",
                            Favorite = false,
                            Name = "JPMorgan Chase & Co.",
                            PreviousPrice = 160.45m,
                            Price = 158.3m
                        },
                        new
                        {
                            Id = "9",
                            Code = "JNJ",
                            Exchange = "NYSE",
                            Favorite = false,
                            Name = "Johnson & Johnson",
                            PreviousPrice = 161.2m,
                            Price = 162.85m
                        },
                        new
                        {
                            Id = "10",
                            Code = "V",
                            Exchange = "NYSE",
                            Favorite = true,
                            Name = "Visa Inc.",
                            PreviousPrice = 272.4m,
                            Price = 275.9m
                        },
                        new
                        {
                            Id = "11",
                            Code = "WMT",
                            Exchange = "NYSE",
                            Favorite = false,
                            Name = "Walmart Inc.",
                            PreviousPrice = 163.80m,
                            Price = 165.30m
                        },
                        new
                        {
                            Id = "12",
                            Code = "PG",
                            Exchange = "NYSE",
                            Favorite = false,
                            Name = "Procter & Gamble Co.",
                            PreviousPrice = 151.20m,
                            Price = 152.40m
                        },
                        new
                        {
                            Id = "13",
                            Code = "UNH",
                            Exchange = "NYSE",
                            Favorite = false,
                            Name = "UnitedHealth Group Inc.",
                            PreviousPrice = 525.30m,
                            Price = 528.90m
                        },
                        new
                        {
                            Id = "14",
                            Code = "BAC",
                            Exchange = "NYSE",
                            Favorite = false,
                            Name = "Bank of America Corp.",
                            PreviousPrice = 34.20m,
                            Price = 34.85m
                        },
                        new
                        {
                            Id = "15",
                            Code = "KO",
                            Exchange = "NYSE",
                            Favorite = false,
                            Name = "Coca-Cola Company",
                            PreviousPrice = 62.10m,
                            Price = 62.75m
                        },
                        new
                        {
                            Id = "16",
                            Code = "INTC",
                            Exchange = "NASDAQ",
                            Favorite = false,
                            Name = "Intel Corporation",
                            PreviousPrice = 44.80m,
                            Price = 45.20m
                        },
                        new
                        {
                            Id = "17",
                            Code = "NFLX",
                            Exchange = "NASDAQ",
                            Favorite = true,
                            Name = "Netflix Inc.",
                            PreviousPrice = 478.30m,
                            Price = 485.60m
                        },
                        new
                        {
                            Id = "18",
                            Code = "ADBE",
                            Exchange = "NASDAQ",
                            Favorite = false,
                            Name = "Adobe Inc.",
                            PreviousPrice = 558.90m,
                            Price = 562.40m
                        },
                        new
                        {
                            Id = "19",
                            Code = "CRM",
                            Exchange = "NYSE",
                            Favorite = false,
                            Name = "Salesforce Inc.",
                            PreviousPrice = 282.40m,
                            Price = 285.70m
                        },
                        new
                        {
                            Id = "20",
                            Code = "PYPL",
                            Exchange = "NASDAQ",
                            Favorite = false,
                            Name = "PayPal Holdings Inc.",
                            PreviousPrice = 67.50m,
                            Price = 68.90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
