// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockMarketAPI.Data;

#nullable disable

namespace StockMarketAPI.Migrations
{
    [DbContext(typeof(StockDbContext))]
    partial class StockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("StockMarketAPI.Models.Stock", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Favorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreviousPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = "2",
                            Code = "MSFT",
                            Exchange = "NASDAQ",
                            Favorite = true,
                            Name = "Microsoft Corporation",
                            PreviousPrice = 380.1m,
                            Price = 382.75m
                        },
                        new
                        {
                            Id = "4",
                            Code = "AMZN",
                            Exchange = "NASDAQ",
                            Favorite = true,
                            Name = "Amazon.com Inc.",
                            PreviousPrice = 142.9m,
                            Price = 145.25m
                        },
                        new
                        {
                            Id = "5",
                            Code = "GOOGL",
                            Exchange = "NASDAQ",
                            Favorite = false,
                            Name = "Alphabet Inc.",
                            PreviousPrice = 140.2m,
                            Price = 138.65m
                        },
                        new
                        {
                            Id = "6",
                            Code = "META",
                            Exchange = "NASDAQ",
                            Favorite = false,
                            Name = "Meta Platforms Inc.",
                            PreviousPrice = 318.75m,
                            Price = 325.4m
                        },
                        new
                        {
                            Id = "7",
                            Code = "NVDA",
                            Exchange = "NASDAQ",
                            Favorite = true,
                            Name = "NVIDIA Corporation",
                            PreviousPrice = 478.9m,
                            Price = 485.2m
                        },
                        new
                        {
                            Id = "8",
                            Code = "JPM",
                            Exchange = "NYSE",
                            Favorite = false,
                            Name = "JPMorgan Chase & Co.",
                            PreviousPrice = 160.45m,
                            Price = 158.3m
                        },
                        new
                        {
                            Id = "9",
                            Code = "JNJ",
                            Exchange = "NYSE",
                            Favorite = false,
                            Name = "Johnson & Johnson",
                            PreviousPrice = 161.2m,
                            Price = 162.85m
                        },
                        new
                        {
                            Id = "10",
                            Code = "V",
                            Exchange = "NYSE",
                            Favorite = true,
                            Name = "Visa Inc.",
                            PreviousPrice = 272.4m,
                            Price = 275.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
